import './global.css';
import Header from './shared/widgets';

export const metadata = {
  title: 'Multi Vender Platform ' ,
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Header />
        {children}
      </body>
    </html>
  )
}
